### ISSUE TITLE
Error in the example?

### ISSUE THREAD

**Issue by AkosLukacs** [dart-league/serializable#6]
Hi!

Just tried to run the example, and kind-of works. Code generation ok, creates the same file as in the Exmaples folder. But some of the examples fail:

@ main.dart:29:8
``` dart
  print('p2: {id: ${p2.id}, name: ${p2.name}, address.id: ${p2.address
      .id}}');  // this ".id" is line 29

// the exception: 
Unhandled exception:
NoSuchMethodError: Class '_InternalLinkedHashMap' has no instance getter 'id'.
Receiver: _LinkedHashMap len:1
Tried calling: id
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      main (file:///C:/Dev/dart_qs/bin/main.dart:29:8)
```
Apparently it's not an `Address` object, but a hashmap:

``` dart
print('p2: {id: ${p2.id}, name: ${p2.name}, address.id: ${p2.address}}');
```
 prints `p2: {id: 2, name: person 2, address.id: {id: 1}}`

``` dart
print('p2.address is: ${p2.address.runtimeType.toString()}');
```
prints `p2.address is: _InternalLinkedHashMap`

Any idea why this doesn't work, is there a problem on my side, or there was some breaking change in Dart itself?
My dart version: `Dart VM version: 1.24.2 (Thu Jun 22 08:55:56 2017) on "windows_x64"`

Thanks!

**Comment by luisvt** [comment]
let me check
